version: "3.9"

services:
  netscan-setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: netscan-setup
    env_file:
      - docker/docker.env
    volumes:
      - es_certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ -z "$ELASTIC_PASSWORD" ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ -z "$KIBANA_PASSWORD" ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elasticsearch\n"\
          "    dns:\n"\
          "      - elasticsearch\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/elasticsearch/elasticsearch.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - netscan-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: netscan-elasticsearch
    env_file:
      - docker/docker.env    
    environment:
      - node.name=elasticsearch
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - es_certs:/usr/share/elasticsearch/config/certs
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - netscan-network
    depends_on:
      - netscan-setup
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  netscan-kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.7.0
    env_file:
      - docker/docker.env    
    volumes:
      - es_certs:/usr/share/kibana/config/certs
      - kb_data:/usr/share/kibana/data
    container_name: netscan-kibana
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - netscan-network
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=$KIBANA_PASSWORD
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  bloodhound-postgres:
    container_name: netscan-bloodhound-postgres
    image: docker.io/library/postgres:13.2
    env_file:
      - docker/docker.env
    #network_mode: "host"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    # Database ports are disabled by default. Please change your database password to something secure before uncommenting
    # ports:
    #   - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE} -h 127.0.0.1 -p 5432"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - netscan-network

  bloodhound-neo4j:
    container_name: netscan-bloodhound-neo4j
    image: docker.io/library/neo4j:4.4
    env_file:
      - docker/docker.env
    #network_mode: "host"
    volumes:
      - bloodhound_data:/data
    ports:
      - "127.0.0.1:${NEO4J_WEB_PORT}:7474"
      - "127.0.0.1:${NEO4J_DB_PORT}:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_dbms_memory_heap_initial__size}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_dbms_memory_heap_max__size}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_dbms_memory_pagecache_size}
      - NEO4J_dbms_allow__upgrade=${NEO4J_ALLOW_UPGRADE:-true}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O /dev/null -q http://localhost:${NEO4J_WEB_PORT:-7474} || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - netscan-network

  bloodhound-app:
    container_name: netscan-bloodhound-app
    image: docker.io/specterops/bloodhound:${BLOODHOUND_TAG:-latest}
    env_file:
      - docker/docker.env
    #network_mode: "host"
    environment:
      - bhe_disable_cypher_qc=${bhe_disable_cypher_qc:-false}
    ports:
      - 127.0.0.1:${BLOODHOUND_PORT}:8080
    volumes:
      - ./docker/bloodhound.config.json:/bloodhound.config.json:ro
    depends_on:
      bloodhound-postgres:
        condition: service_healthy
      bloodhound-neo4j:
        condition: service_healthy
    networks:
      - netscan-network

  gowitness:
    container_name: netscan-gowitness
    image: ghcr.io/sensepost/gowitness
    command: gowitness report server --host 0.0.0.0 --port 7171
    ports:
      - 127.0.0.1:7171:7171
    volumes:
      - gowitness-data:/data
    networks:
      - netscan-network

volumes:
  es_certs:
    driver: local
  es_data:
    driver: local
  kb_data:
    driver: local
  bloodhound_data:
    driver: local
  postgres_data:
    driver: local
  gowitness-data:
    driver: local

networks:
  netscan-network:
    name: netscan-network
    driver: bridge
